---
- name: Install Linux development packages
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  when: ansible_system == "Linux"

- name: Create Linux development directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ directories }}"
  when: ansible_system == "Linux"