---
- name: Install required packages
  package:
    name:
      - joystick
      - mednafen
    state: present
  become: yes
  when: ansible_system == "Linux"

- name: Create Mednafen configuration directory
  file:
    path: "{{ mednafen_config_dir }}"
    state: directory
    mode: '0755'
  when: ansible_system == "Linux"

- name: Create ROM directory
  file:
    path: "{{ rom_dir }}"
    state: directory
    mode: '0755'
  when: ansible_system == "Linux"

- name: Download Sonic & Knuckles ROM
  get_url:
    url: "{{ sonic_knuckles_rom_url }}"
    dest: "{{ rom_dir }}/Sonic & Knuckles (World).zip"
    mode: '0644'
  when:
    - ansible_system == "Linux"
    - sonic_knuckles_rom_url is defined
    - not (lookup('file', '{{ rom_dir }}/Sonic & Knuckles (World).zip') is defined)

- name: Create Mednafen configuration file
  copy:
    content: |
      # Mednafen Configuration for Gaming

      # Audio Settings
      sound.driver {{ audio_driver }}
      sound.device {{ audio_device }}
      sound.rate {{ audio_rate }}
      sound.buffer_time {{ audio_buffer_time }}

      # Genesis/Mega Drive Settings
      md.xscale {{ md_xscale }}
      md.yscale {{ md_yscale }}
      md.special {{ md_special }}
      md.region {{ md_region }}
      md.correct_aspect {{ md_correct_aspect }}

      # Controller Settings
      md.input.mouse_sensitivity 1.00

      ## Genesis/MegaDrive; Virtual Port 1; 3-Button Gamepad
      md.input.port1 gamepad
      md.input.port1.gamepad.a joystick 0 0
      md.input.port1.gamepad.b joystick 0 1
      md.input.port1.gamepad.c joystick 0 2
      md.input.port1.gamepad.start joystick 0 3
      md.input.port1.gamepad.up joystick 0 1
      md.input.port1.gamepad.down joystick 0 1
      md.input.port1.gamepad.left joystick 0 0
      md.input.port1.gamepad.right joystick 0 0

      ## Genesis/MegaDrive; Virtual Port 2; 3-Button Gamepad
      md.input.port2 gamepad
      md.input.port2.gamepad.a joystick 1 0
      md.input.port2.gamepad.b joystick 1 1
      md.input.port2.gamepad.c joystick 1 2
      md.input.port2.gamepad.start joystick 1 3
      md.input.port2.gamepad.up joystick 1 1
      md.input.port2.gamepad.down joystick 1 1
      md.input.port2.gamepad.left joystick 1 0
      md.input.port2.gamepad.right joystick 1 0

      # Video Settings
      video.driver {{ video_driver }}
      video.fs {{ video_fs }}
      vb.xscale {{ video_xscale }}
      vb.yscale {{ video_yscale }}
      vb.xscalefs {{ video_xscalefs }}
      vb.yscalefs {{ video_yscalefs }}
      vb.special none
      video.glvsync 1
      video.disable_composition 0

      # Input Settings
      input.autofirefreq 0
      input.ckdelay 0
    dest: "{{ mednafen_config_dir }}/mednafen.cfg"
    mode: '0644'
  when: ansible_system == "Linux"

- name: Create applications directory
  file:
    path: "{{ applications_dir }}"
    state: directory
    mode: '0755'
  when: ansible_system == "Linux"

- name: Create desktop launcher
  copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Sonic & Knuckles
      Comment=Play Sonic & Knuckles with Mednafen
      Exec=mednafen "{{ rom_dir }}/Sonic & Knuckles (World).zip"
      Icon=applications-games
      Terminal=false
      Categories=Game;Emulator;
      StartupNotify=true
      MimeType=application/x-genesis-rom;
    dest: "{{ applications_dir }}/sonic-knuckles.desktop"
    mode: '0755'
  when: ansible_system == "Linux"
