---
# Ansible Galaxy requirements
# This file can be used to install external roles from Ansible Galaxy

# Collections for Windows support
collections:
  - name: ansible.windows
    version: ">=1.7.0"
  - name: community.windows
    version: ">=1.0.0"
  - name: chocolatey.chocolatey
    version: ">=1.0.0"

# Example roles (uncomment as needed):
# - name: geerlingguy.docker
#   version: "4.1.0"
# - src: https://github.com/geerlingguy/ansible-role-docker
#   name: docker
#   version: "4.1.0"