---
# Ansible Galaxy requirements
# This file can be used to install external roles from Ansible Galaxy
# Example:
# - name: geerlingguy.docker
#   version: "4.1.0"
# - src: https://github.com/geerlingguy/ansible-role-docker
#   name: docker
#   version: "4.1.0"

# Currently no external dependencies
# Add roles here as needed