---
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  when: ansible_system == "Linux"

- name: Create .config/nvim directory
  file:
    path: "{{ nvim_config_dir }}"
    state: directory
    mode: '0755'
  when: ansible_system == "Linux"

- name: Deploy init.vim with auto-updating buffer configuration
  template:
    src: init.vim.j2
    dest: "{{ nvim_config_file }}"
    mode: "{{ nvim_config_mode }}"
  notify: Neovim configuration deployed
  when: ansible_system == "Linux"
