---
galaxy_info:
  author: your_name
  description: Windows WSL2 setup and configuration role
  company: your_company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 10
        - 11
  galaxy_tags:
    - windows
    - wsl
    - wsl2
    - development
    - setup

dependencies: []