---
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
  become: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ directories }}"

- name: Deploy tmux configuration
  template:
    src: tmux.conf.j2
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    mode: '0644'
