---
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  when: ansible_system == "Linux"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ directories }}"
  when: ansible_system == "Linux"

- name: Configure git user name
  git_config:
    name: "user.name"
    value: "{{ git_user_name }}"
    scope: global
  when:
    - ansible_system == "Linux"
    - git_user_name is defined

- name: Configure git user email
  git_config:
    name: "user.email"
    value: "{{ git_user_email }}"
    scope: global
  when:
    - ansible_system == "Linux"
    - git_user_email is defined

- name: Configure git aliases
  git_config:
    name: "alias.{{ item.alias }}"
    value: "{{ item.command }}"
    scope: global
  loop: "{{ git_aliases }}"
  when: ansible_system == "Linux"

- name: Set git default branch name
  git_config:
    name: "init.defaultBranch"
    value: "main"
    scope: global
  when: ansible_system == "Linux"

- name: Configure git pull strategy
  git_config:
    name: "pull.rebase"
    value: "false"
    scope: global
  when: ansible_system == "Linux"

- name: Configure git color output
  git_config:
    name: "color.ui"
    value: "auto"
    scope: global
  when: ansible_system == "Linux"

- name: Configure git to prune remote branches
  git_config:
    name: "remote.origin.prune"
    value: "true"
    scope: global
  when: ansible_system == "Linux"
