---
all:
  children:
    gaming:
      hosts:
        localhost:
          ansible_connection: local
    development:
      hosts:
        localhost:
          ansible_connection: local
      children:
        linux_dev:
          hosts:
            localhost:
              ansible_connection: local
            # Add actual Linux development machines here
            # dev-linux-1:
            #   ansible_host: 192.168.1.50
            #   ansible_user: developer
            #   ansible_ssh_private_key_file: ~/.ssh/dev_key
        windows_dev:
          hosts:
            # Add actual Windows development machines here
            # dev-windows-1:
            #   ansible_host: 192.168.1.51
            #   ansible_connection: winrm
            #   ansible_user: "{{ ansible_user | default('Administrator') }}"
            #   ansible_password: "{{ ansible_password | default('') }}"
            #   ansible_winrm_server_cert_validation: ignore
            #   ansible_winrm_transport: basic
    production:
      children:
        web_servers:
          hosts:
            # Add your production web servers here
            # web-1:
            #   ansible_host: 192.168.1.10
            #   ansible_user: ubuntu
            #   ansible_ssh_private_key_file: ~/.ssh/prod_key
            # web-2:
            #   ansible_host: 192.168.1.11
            #   ansible_user: ubuntu
            #   ansible_ssh_private_key_file: ~/.ssh/prod_key
        database_servers:
          hosts:
            # Add your production database servers here
            # db-1:
            #   ansible_host: 192.168.1.20
            #   ansible_user: ubuntu
            #   ansible_ssh_private_key_file: ~/.ssh/prod_key
            # db-2:
            #   ansible_host: 192.168.1.21
            #   ansible_user: ubuntu
            #   ansible_ssh_private_key_file: ~/.ssh/prod_key
