---
# Default variables for Windows WSL2 setup role

# WSL distributions to install
wsl_distributions:
  - name: "Ubuntu"
    download_url: "https://aka.ms/wslubuntu2004"
  - name: "Ubuntu-22.04"
    download_url: "https://aka.ms/wslubuntu2204"

# Default WSL distribution
wsl_default_distribution: "Ubuntu-22.04"

# WSL configuration
wsl_config:
  memory: "4GB"
  processors: 2
  swap: "2GB"
  localhostForwarding: true

# Development tools to install
windows_dev_tools:
  - microsoft-windows-terminal
  - git
  - vscode
  - chocolatey

# Development directories to create
dev_directories:
  - "C:\\Users\\{{ ansible_user }}\\Documents\\Repositories"
  - "C:\\Users\\{{ ansible_user }}\\Documents\\Scripts"
  - "C:\\Users\\{{ ansible_user }}\\Documents\\Configs"
  - "C:\\Users\\{{ ansible_user }}\\Documents\\WSL"