---
# Development Environment Playbook
# This playbook targets only development hosts

- name: Configure Gaming Environment (Linux Development)
  hosts: linux_dev
  connection: local
  become: no
  roles:
    - mednafen-gaming

- name: Development Environment Setup (Linux Development)
  hosts: linux_dev
  connection: local
  become: no
  roles:
    - common
    - linux-dev
    - git-config
    - nvim-config

- name: Windows WSL2 Setup (Windows Development)
  hosts: windows_dev
  connection: winrm
  become: no
  roles:
    - windows-wsl2-setup
    - windows-dev