---
# Windows-only playbook for WSL2 setup
- name: Windows WSL2 Setup and Development Environment
  hosts: windows_hosts
  connection: winrm
  become: no
  gather_facts: yes
  
  tasks:
    - name: Check if running on Windows
      win_debug:
        msg: "Running on Windows {{ ansible_distribution_version }}"
      when: ansible_system == "Windows"

    - name: Enable WSL feature
      win_feature:
        name: Microsoft-Windows-Subsystem-Linux
        state: present
      become: yes

    - name: Enable Virtual Machine Platform feature
      win_feature:
        name: VirtualMachinePlatform
        state: present
      become: yes

    - name: Set WSL version to 2
      win_shell: wsl --set-default-version 2
      become: yes

    - name: Download WSL distributions
      win_get_url:
        url: "{{ item.download_url }}"
        dest: "C:\\temp\\{{ item.name }}.appx"
      loop: "{{ wsl_distributions }}"
      when: not ansible_check_mode

    - name: Install WSL distributions
      win_shell: |
        Add-AppxPackage "C:\\temp\\{{ item.name }}.appx"
      loop: "{{ wsl_distributions }}"
      become: yes
      when: not ansible_check_mode

    - name: Set default WSL distribution
      win_shell: wsl --set-default "{{ wsl_default_distribution }}"
      become: yes

    - name: Update WSL kernel
      win_shell: wsl --update
      become: yes

    - name: Create WSL configuration directory
      win_file:
        path: "C:\\Users\\{{ ansible_user }}\\.wslconfig"
        state: directory

    - name: Configure WSL settings
      win_copy:
        content: |
          [wsl2]
          memory={{ wsl_config.memory }}
          processors={{ wsl_config.processors }}
          swap={{ wsl_config.swap }}
          localhostForwarding={{ wsl_config.localhostForwarding | lower }}
        dest: "C:\\Users\\{{ ansible_user }}\\.wslconfig"

    - name: Install Chocolatey (if not present)
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      become: yes
      when: ansible_check_mode == false

    - name: Install development tools
      win_chocolatey:
        name: "{{ item }}"
        state: present
      become: yes
      when: ansible_check_mode == false
      loop: "{{ windows_dev_tools }}"

    - name: Create development directory structure
      win_file:
        path: "{{ item }}"
        state: directory
      loop: "{{ dev_directories }}"

    - name: Display WSL status
      win_shell: wsl --list --verbose
      register: wsl_status

    - name: Show WSL status
      win_debug:
        var: wsl_status.stdout_lines

  vars:
    wsl_distributions:
      - name: "Ubuntu"
        download_url: "https://aka.ms/wslubuntu2004"
      - name: "Ubuntu-22.04"
        download_url: "https://aka.ms/wslubuntu2204"
    wsl_default_distribution: "Ubuntu-22.04"
    wsl_config:
      memory: "4GB"
      processors: 2
      swap: "2GB"
      localhostForwarding: true
    windows_dev_tools:
      - microsoft-windows-terminal
      - git
      - vscode
    dev_directories:
      - "C:\\Users\\{{ ansible_user }}\\Documents\\Repositories"
      - "C:\\Users\\{{ ansible_user }}\\Documents\\Scripts"
      - "C:\\Users\\{{ ansible_user }}\\Documents\\Configs"
      - "C:\\Users\\{{ ansible_user }}\\Documents\\WSL"